application: viiflog
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /blog
  script: home.app
- url: /static
  static_dir: static
- url: /blog/.*
  script: home.app
- url: /.*
  script: home.app
#- url: /(.*\.(gif|png|jpg))
#  static_files: static/\1
#  upload: static/(.*\.(gif|png|jpg))

#- url: /admin/.*
#  script: admin.app
#  login: admin

#- url: /.*
#  script: not_found.app

libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: latest


skip_files:
- ^\.git(/.*)?
- (.*/)?.*~
- (.*/)?.*\.py[co]

